import Foundation
import Testing

@testable import FireweaveStart

@Suite("Start profile: channel and build info")
struct ChannelTests {
  @Test func theChannelRuleIsAPureFunctionOfTheVersion() {
    let cases: [(version: String, channel: FireweaveChannel)] = [
      ("2.4.0", .production),
      ("2.4.0-staging.1", .staging),
      ("2.4.1-staging.12", .staging),
      ("2.4.0-staging", .production),
      ("2.4.0-rc.1", .production),
      ("", .production),
    ]
    for (version, channel) in cases {
      #expect(channelForVersion(version) == channel, "\(version)")
    }
  }

  @Test func eachChannelHasItsOwnDefaultHost() {
    #expect(FireweaveChannel.production.defaultURL == "https://app-server.fireweave.ai")
    #expect(FireweaveChannel.staging.defaultURL == "https://staging-app-server.fireweave.ai")
  }

  @Test func bothChannelHostsAreInTheCoreDefaultAllowlist() {
    for channel in [FireweaveChannel.production, .staging] {
      let host = URLComponents(string: channel.defaultURL)?.host ?? ""
      #expect(defaultAllowedHosts.contains(host), "\(host)")
    }
  }

  /// `tools/release/version.sh apply swift` writes both values; a stamp
  /// whose channel disagrees with its version would send a staging build to
  /// production (or the reverse).
  @Test func theBuildStampIsConsistent() {
    #expect(FireweaveChannel(rawValue: BuildInfo.sdkChannel) != nil)
    #expect(channelForVersion(BuildInfo.sdkVersion).rawValue == BuildInfo.sdkChannel)
    #expect(FireweaveChannel.current.rawValue == BuildInfo.sdkChannel)
  }

  @Test func theBuildStampKeepsTheGeneratedShape() throws {
    let path = URL(fileURLWithPath: #filePath)
      .deletingLastPathComponent()  // FireweaveStartTests/
      .deletingLastPathComponent()  // Tests/
      .deletingLastPathComponent()  // sdks/swift/
      .appendingPathComponent("Sources/FireweaveStart/BuildInfo.swift")
    let text = try String(contentsOf: path, encoding: .utf8)
    #expect(text.hasPrefix("// GENERATED by tools/release/version.sh apply swift"))
    #expect(text.contains("static let sdkVersion = \"\(BuildInfo.sdkVersion)\""))
    #expect(text.contains("static let sdkChannel = \"\(BuildInfo.sdkChannel)\""))
  }
}

@Suite("Start profile: instance key")
struct InstanceKeyTests {
  @Test func fnv1a64MatchesTheReferenceVectors() {
    #expect(fnv1a64("") == "cbf29ce484222325")
    #expect(fnv1a64("a") == "af63dc4c8601ec8c")
    // The same value the Node, Go, Java and Rust start profiles give.
    #expect(fnv1a64("api-pod-1") == "8148fc8bb0e952ef")
  }

  @Test func theSourcesApplyInOrder() {
    let withId: (String) -> String? = { name in
      ["FIREWEAVE_INSTANCE_ID": "worker-7", "HOSTNAME": "env-host"][name]
    }
    let empty: (String) -> String? = { _ in nil }

    let option = deriveInstanceKey(option: " cron-1 ", env: withId, hostName: { "api-pod-1" })
    #expect(option == InstanceKey(value: "cron-1", source: .option))

    let fromEnv = deriveInstanceKey(option: nil, env: withId, hostName: { "api-pod-1" })
    #expect(fromEnv == InstanceKey(value: "worker-7", source: .environment))

    let fromHost = deriveInstanceKey(option: nil, env: empty, hostName: { "api-pod-1" })
    #expect(fromHost == InstanceKey(value: "inst_8148fc8bb0e952ef", source: .host))

    let hostEnv: (String) -> String? = { name in name == "HOSTNAME" ? "api-pod-1" : nil }
    let fromHostEnv = deriveInstanceKey(option: nil, env: hostEnv, hostName: { "other" })
    #expect(fromHostEnv.value == "inst_8148fc8bb0e952ef")

    let first = deriveInstanceKey(option: nil, env: empty, hostName: { nil })
    let second = deriveInstanceKey(option: nil, env: empty, hostName: { nil })
    #expect(first.source == .random)
    #expect(first.value != second.value)
    #expect(first.value.hasPrefix("inst_"))
    #expect(first.value.count == "inst_".count + 32)
  }
}

@Suite("Start profile: flags")
struct FlagsTests {
  @Test func defineFlagsReturnsItsArgument() {
    let flags = defineFlags([
      "new-checkout": .local(true, description: "New checkout flow"),
      "old-banner": false,
    ])
    let expected = FireweaveFlag(localValue: true, description: "New checkout flow")
    #expect(flags["new-checkout"] == expected)
    #expect(flags["old-banner"]?.localValue == false)
    #expect(localSeeds(flags) == ["new-checkout": true, "old-banner": false])
  }

  @Test func badKeysAreConfigurationErrorsNamingTheKey() {
    let tooLong = String(repeating: "k", count: 300)
    for key in ["", tooLong, "line\nbreak"] {
      guard case .failure(let error) = normalizeFlags([key: true]) else {
        Issue.record("\(key.prefix(10)) should be rejected")
        continue
      }
      #expect(error.kind == .configuration)
      #expect(error.message.contains("is not a valid control point key"))
    }
  }

  @Test func theSignatureIgnoresDescriptionsAndOrder() {
    let first: FireweaveFlags = ["b": .local(true, description: "x"), "a": false]
    let second: FireweaveFlags = ["a": false, "b": true]
    #expect(flagsSignature(first) == flagsSignature(second))
    #expect(flagsSignature(first) != flagsSignature(["a": true, "b": true]))
  }
}

@Suite("Start profile: keys")
struct KeyShapeTests {
  @Test func analyticsVendorKeysAreRecognisedByShape() {
    #expect(isAnalyticsVendorKey(vendorPrefix("c") + "abc"))
    #expect(isAnalyticsVendorKey(vendorPrefix("x") + "abc"))
    #expect(!isAnalyticsVendorKey("ph_abc"))
    #expect(!isAnalyticsVendorKey("phC_abc"))
    #expect(!isAnalyticsVendorKey(testProjectKey))
  }

  @Test func onlyPlainTokensAreEchoed() {
    #expect(isEchoable("production"))
    #expect(isEchoable("eu-west.1"))
    #expect(!isEchoable(""))
    #expect(!isEchoable(String(repeating: "a", count: 33)))
    #expect(!isEchoable("has space"))
    #expect(!isEchoable(testProjectKey))
    #expect(!isEchoable(testBrowserKey))
    #expect(!isEchoable(vendorPrefix("c") + "abc"))
  }
}
