// GENERATED by tools/release/version.sh apply swift — do not edit by hand.
// The start profile reads sdkChannel to choose its default fw-server host
// (docs/adr/0012-start-profile.md).
enum BuildInfo {
  static let sdkVersion = "2.2.0"
  static let sdkChannel = "production"
}
