// GENERATED by tools/release/version.sh apply dart — do not edit by hand.
// The start profile reads buildSdkChannel to choose its default fw-server
// host (docs/adr/0012-start-profile.md). test/start_build_info_test.dart
// pins buildSdkVersion to pubspec.yaml, so a release that forgets to stamp
// fails CI.
const String buildSdkVersion = '2.2.0';
const String buildSdkChannel = 'production';
