// GENERATED by tools/release/version.sh apply server — do not edit by hand.
// The start profile reads SDK_CHANNEL to choose its default fw-server host
// (docs/adr/0011-start-profile.md). test/unit/start-build-info.test.ts pins
// SDK_VERSION to package.json, so a release that forgets to stamp fails CI.
export const SDK_VERSION = '2.2.0';
export const SDK_CHANNEL: 'staging' | 'production' = 'production';
